image: "rust:latest"

stages:
  - build
  - package

# Use cargo to test the project
linux build:
  stage: build
  script:
    - rustup default nightly
    - cargo build --release
    - strip target/release/mmm
  cache:
    paths:
      - target/release
  artifacts:
    paths:
      - target/release/mmm

linux packages:
  stage: package
  image: "tenzer/fpm:no-entrypoint"
  dependencies:
    - linux build
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir -p ./source/usr/bin
    - cp target/release/mmm ./source/usr/bin
    # TODO: static version here has to be dynamic (tag probably)
    - fpm -s dir -C ./source -t deb -n mmm -v 0.0.1 .
    - fpm -s dir -C ./source -t rpm -n mmm -v 0.0.1 .
    - fpm -s dir -C ./source -t pacman -n mmm -v 0.0.1 .
  artifacts:
    paths:
      - '*.deb'
      - '*.rpm'
      - '*.pkg.tar.xz' # pacman
