image: "golang:latest"

stages:
  - build
  - package

linux build:
  stage: build
  script:
    - go build -ldflags="-s -w" -o ./out/minepkg
  artifacts:
    paths:
      - out/minepkg

linux packages:
  stage: package
  image: "tenzer/fpm:no-entrypoint"
  dependencies:
    - linux build
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir -p ./source/usr/bin
    - cp out/minepkg ./source/usr/bin
    # TODO: static version here has to be dynamic (tag probably)
    - fpm -s dir -C ./source -t deb -n minepkg -v 0.0.1 .
    - fpm -s dir -C ./source -t rpm -n minepkg -v 0.0.1 .
    - fpm -s dir -C ./source -t pacman -n minepkg -v 0.0.1 .
  artifacts:
    paths:
      - '*.deb'
      - '*.rpm'
      - '*.pkg.tar.xz' # pacman
