# WARNING: This package might not work with future versions
#   of minepkg and might need to be updated then.
# This is a preview version of the minepkg.toml format!
version = 0

[package]
type = "modpack"

# This is the name of your modpack (in case you want to publish it)
# Please choose a unique name without spaces or special characters
name = "examplepack"
description = ""
version = "0.0.1"

# These are global requirements that apply to all dependencies and the pack itself
[requirements]
minecraft-version = "1.12.x"

# All packages included in your modpack
[dependencies]
