name: main builds

on:
  push:
    branches: [ main ]

jobs:
  mainBuilds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --snapshot --skip-publish
      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: dist
      - runs: |
          VERSION="$(git describe --abbrev=0)-next"
          echo -e '{
            "channel": "dev",
            "version": "'$VERSION'",
            "gitHash": "${{ github.sha }}",
            "binaries": {
              "win": "https://get.minepkg.io/dev/minepkg_windows_amd64/minepkg.exe",
              "macos": "https://get.minepkg.io/dev/minepkg_darwin_amd64/minepkg",
              "linux": "https://get.minepkg.io/dev/minepkg_linux_amd64/minepkg"
            }
          }' > dist/latest-version.json
      - id: upload-files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: dist
          destination: minepkg-client/dev/
