name: main builds

on:
  push:
    branches: [ main ]

jobs:
  mainBuilds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --snapshot --skip-publish
      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: dist
